<script lang="ts">
 import { onMount } from 'svelte';
 import { beforeNavigate } from '$app/navigation';
 import { createDefaultCharacter, abilityNames, skillNames } from '$lib/character/defaults';
 import { formatModifier, modifier, passivePerception, proficiencyBonus, savingThrowModifier, skillModifier } from '$lib/character/calculations';
 import { canUseFilePicker, downloadCharacter, fileName, serialize, writeCharacter, type CharacterFileHandle } from '$lib/character/file';
 import { parseCharacter } from '$lib/character/validation';
 import type { Character, SessionNote } from '$lib/character/types';
 let character = $state<Character>(createDefaultCharacter()); let loaded = $state(false); let dirty = $state(false); let error = $state(''); let handle = $state<CharacterFileHandle | null>(null); let fileInput = $state<HTMLInputElement>(); let activeTab = $state('overview'); let savedSnapshot = '';
 const tabs = ['overview','combat','spells','inventory','features','notes'];
 const label = (value: string) => value.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase());
 function markDirty() { if (character) dirty = serialize(character) !== savedSnapshot; }
 function sessionId(): string { return typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `session-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
 function addSessionNote() { if (!character) return; const now = new Date(); const note: SessionNote = { id: sessionId(), title: 'Session', date: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`, notes: '' }; character.notes.sessionNotes = [note, ...character.notes.sessionNotes]; markDirty(); }
 function createNew() { character = createDefaultCharacter(); loaded = true; handle = null; error = ''; savedSnapshot = ''; dirty = true; }
 async function openFile(file: File) { try { character = parseCharacter(await file.text()); loaded = true; savedSnapshot = serialize(character); dirty = false; error = ''; handle = null; } catch (e) { error = e instanceof Error ? e.message : 'Unable to read this character file.'; } }
 async function openWithPicker() { if (!canUseFilePicker()) { fileInput?.click(); return; } try { const picker = (window as unknown as { showOpenFilePicker: (options?: unknown) => Promise<Array<{ getFile: () => Promise<File>; createWritable: () => Promise<unknown> }>> }).showOpenFilePicker; const [picked] = await picker({ types: [{ description: 'D&D Portal character', accept: { 'application/json': ['.json'] } }] }); handle = picked as unknown as CharacterFileHandle; await openFile(await picked.getFile()); handle = picked as unknown as CharacterFileHandle; } catch { /* cancelled */ } }
 async function save(asNew = false) { if (!character) return; try { if (!asNew && handle && 'createWritable' in handle) await writeCharacter(character, handle); else if (canUseFilePicker()) { const picker = (window as unknown as { showSaveFilePicker: (options?: unknown) => Promise<CharacterFileHandle> }).showSaveFilePicker; const nextHandle = await picker({ suggestedName: fileName(character), types: [{ description: 'D&D Portal character', accept: { 'application/json': ['.json'] } }] }); await writeCharacter(character, nextHandle); handle = nextHandle; } else await downloadCharacter(character); savedSnapshot = serialize(character); dirty = false; } catch { /* cancelled or unavailable; remain dirty */ } }
 beforeNavigate((navigation) => { if (dirty && !navigation.to?.url.pathname.startsWith('/my-character')) { if (!window.confirm('You have unsaved changes. If you leave this page, those changes will be lost.')) navigation.cancel(); } });
 onMount(() => { const beforeUnload = (event: BeforeUnloadEvent) => { if (!dirty) return; event.preventDefault(); event.returnValue = ''; }; const key = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 's' && character) { event.preventDefault(); void save(event.shiftKey); } }; window.addEventListener('beforeunload', beforeUnload); window.addEventListener('keydown', key); return () => { window.removeEventListener('beforeunload', beforeUnload); window.removeEventListener('keydown', key); }; });
</script>

<svelte:head><title>My Character | D&D Portal Wiki</title><meta name="description" content="Edit a D&D character locally with D&D Portal." /></svelte:head>

{#if !loaded}
 <article class="character-page character-page--loader"><div class="character-loader" role="region" aria-label="Open character file" ondragover={(e) => e.preventDefault()} ondrop={(e) => { e.preventDefault(); const file = e.dataTransfer?.files?.[0]; if (file) void openFile(file); }}><p class="eyebrow">D&D PORTAL TOOL</p><h1>My Character</h1><p class="lead">A portable character sheet that stays with you. Open a JSON character file to start editing.</p><p class="privacy-note">Your character file stays on your device. It is never uploaded.</p><div class="loader-actions"><button class="button button--primary" onclick={openWithPicker}>Open character JSON</button><button class="button" onclick={createNew}>Create new character</button></div><input bind:this={fileInput} class="visually-hidden" type="file" accept=".json,application/json" onchange={(e) => { const file = (e.currentTarget as HTMLInputElement).files?.[0]; if (file) void openFile(file); }} />{#if error}<p class="form-error" role="alert">{error}</p>{/if}<p class="muted">Or drag and drop a .json file here.</p></div></article>
{:else}
 <article class="character-page"><header class="character-header"><div><p class="eyebrow">LOCAL CHARACTER SHEET</p><h1>{character.character.name || 'Unnamed character'}</h1><p class="character-subtitle">{character.character.race || 'Race'} · {character.character.class || 'Class'} level {character.character.level}</p></div><div class="character-actions"><span class:status--dirty={dirty} class="status">{dirty ? '● Unsaved changes' : '✓ Saved'}</span><button class="button button--primary" onclick={() => void save()}>Save</button><button class="button" onclick={() => void save(true)}>Save as</button><button class="button button--quiet" onclick={() => { loaded = false; handle = null; }}>Close</button></div></header>
  <nav class="character-tabs" aria-label="Character sections">{#each tabs as tab}<button class:active={activeTab === tab} onclick={() => activeTab = tab}>{label(tab)}</button>{/each}</nav>
  {#if activeTab === 'overview'}<section class="character-grid"><div class="panel"><h2>Identity</h2><div class="form-grid">{#each [['name','Character name'],['player','Player'],['race','Race'],['class','Class'],['subclass','Subclass'],['background','Background'],['alignment','Alignment']] as field}<label>{field[1]}<input value={character.character[field[0] as keyof typeof character.character] as string} oninput={(e) => { character!.character[field[0] as keyof typeof character.character] = (e.currentTarget as HTMLInputElement).value as never; markDirty(); }} /></label>{/each}<label>Level<input type="number" min="1" max="20" bind:value={character.character.level} oninput={markDirty} /></label><label>XP<input type="number" min="0" bind:value={character.character.xp} oninput={markDirty} /></label></div></div><div class="panel"><h2>Ability scores</h2><div class="abilities">{#each abilityNames as ability}<label class="ability"><span>{ability.slice(0,3).toUpperCase()}</span><input type="number" min="1" max="30" bind:value={character.abilities[ability]} oninput={markDirty} /><strong>{formatModifier(modifier(character.abilities[ability]))}</strong></label>{/each}</div><div class="stat-strip"><span>Proficiency <strong>{formatModifier(proficiencyBonus(character.character.level))}</strong></span><span>Armor class <strong>{character.combat.armorClass}</strong></span><span>Initiative <strong>{formatModifier(modifier(character.abilities.dexterity))}</strong></span><span>Speed <strong>{character.combat.speed}</strong></span><span>Passive perception <strong>{passivePerception(character)}</strong></span></div></div><div class="panel panel--wide"><h2>Skills & saving throws</h2><div class="skills-grid">{#each skillNames as skill}<div class="skill-row"><span class="skill-name">{skill.label}</span><small>{skill.ability.slice(0,3).toUpperCase()}</small><button class:expert={character.skills[skill.key].expertise} class="tag-button" onclick={() => { character!.skills[skill.key].expertise = !character!.skills[skill.key].expertise; character!.skills[skill.key].proficient = true; markDirty(); }}>Expertise</button><input aria-label={`${skill.label} proficiency`} type="checkbox" checked={character.skills[skill.key].proficient} onchange={(e) => { character!.skills[skill.key].proficient = (e.currentTarget as HTMLInputElement).checked; if (!character!.skills[skill.key].proficient) character!.skills[skill.key].expertise = false; markDirty(); }} /><strong>{formatModifier(skillModifier(character, skill.key))}</strong></div>{/each}</div><div class="save-grid">{#each abilityNames as ability}<div class="save-row"><input aria-label={`${label(ability)} saving throw proficiency`} type="checkbox" bind:checked={character.savingThrows[ability]} onchange={markDirty} /><span>{label(ability)}</span><strong>{formatModifier(savingThrowModifier(character, ability))}</strong></div>{/each}</div></div></section>{/if}
  {#if activeTab === 'combat'}<section class="character-grid"><div class="panel"><h2>Hit points</h2><div class="hp-control"><button class="button" onclick={() => { character!.combat.currentHp--; markDirty(); }}>−</button><input aria-label="Current hit points" type="number" bind:value={character.combat.currentHp} oninput={markDirty} /><button class="button" onclick={() => { character!.combat.currentHp++; markDirty(); }}>+</button></div><div class="form-grid"><label>Max HP<input type="number" bind:value={character.combat.maxHp} oninput={markDirty} /></label><label>Temporary HP<input type="number" bind:value={character.combat.temporaryHp} oninput={markDirty} /></label><label>Hit dice<input bind:value={character.combat.hitDice.type} oninput={markDirty} /></label><label>Dice total<input type="number" bind:value={character.combat.hitDice.total} oninput={markDirty} /></label></div><label class="check-line"><input type="checkbox" bind:checked={character.combat.inspiration} onchange={markDirty} /> Inspiration</label></div><div class="panel"><h2>Death saves</h2><p class="muted">Successes</p><div class="save-dots">{#each [0,1,2] as dot}<button class:filled={dot < character.combat.deathSaves.successes} onclick={() => { character!.combat.deathSaves.successes = dot + 1 === character!.combat.deathSaves.successes ? dot : dot + 1; markDirty(); }} aria-label={`Success ${dot + 1}`}>✓</button>{/each}</div><p class="muted">Failures</p><div class="save-dots save-dots--failure">{#each [0,1,2] as dot}<button class:filled={dot < character.combat.deathSaves.failures} onclick={() => { character!.combat.deathSaves.failures = dot + 1 === character!.combat.deathSaves.failures ? dot : dot + 1; markDirty(); }} aria-label={`Failure ${dot + 1}`}>×</button>{/each}</div></div><div class="panel panel--wide"><h2>Attacks <button class="button button--small" onclick={() => { character!.attacks.push({name:'',bonus:'',damage:'',damageType:'',notes:''}); markDirty(); }}>Add attack</button></h2>{#each character.attacks as attack, index}<div class="repeat-row"><input aria-label="Attack name" placeholder="Name" bind:value={attack.name} oninput={markDirty} /><input aria-label="Attack bonus" placeholder="Bonus" bind:value={attack.bonus} oninput={markDirty} /><input aria-label="Damage" placeholder="Damage" bind:value={attack.damage} oninput={markDirty} /><input aria-label="Damage type" placeholder="Type" bind:value={attack.damageType} oninput={markDirty} /><button class="button button--quiet" onclick={() => { character!.attacks.splice(index,1); markDirty(); }}>Remove</button></div>{/each}</div></section>{/if}
  {#if activeTab === 'spells'}<section class="character-grid"><div class="panel"><h2>Spellcasting</h2><label>Ability<select bind:value={character.spells.ability} onchange={markDirty}><option value={null}>None</option>{#each abilityNames as ability}<option value={ability}>{label(ability)}</option>{/each}</select></label>{#if character.spells.ability}<div class="stat-strip"><span>Save DC <strong>{8 + proficiencyBonus(character.character.level) + modifier(character.abilities[character.spells.ability])}</strong></span><span>Attack bonus <strong>{formatModifier(proficiencyBonus(character.character.level) + modifier(character.abilities[character.spells.ability]))}</strong></span></div>{/if}</div><div class="panel panel--wide"><h2>Spell slots</h2><div class="slots">{#each Array(9) as _, index}{@const level = String(index + 1)}<label>Level {level}<input aria-label={`Level ${level} maximum slots`} type="number" min="0" bind:value={character.spells.slots[level].max} oninput={markDirty} /><input aria-label={`Level ${level} used slots`} type="number" min="0" bind:value={character.spells.slots[level].used} oninput={markDirty} /></label>{/each}</div></div></section>{/if}
  {#if activeTab === 'inventory'}<section class="character-grid"><div class="panel"><h2>Currency</h2><div class="currency">{#each Object.keys(character.currency) as coin}<label>{coin.toUpperCase()}<input type="number" bind:value={character.currency[coin as keyof typeof character.currency]} oninput={markDirty} /></label>{/each}</div></div><div class="panel panel--wide"><h2>Equipment <button class="button button--small" onclick={() => { character!.equipment.push({id:null,name:'',quantity:1,equipped:false,notes:''}); markDirty(); }}>Add item</button></h2>{#each character.equipment as item, index}<div class="repeat-row"><input aria-label="Item name" placeholder="Item" bind:value={item.name} oninput={markDirty} /><input aria-label="Quantity" type="number" bind:value={item.quantity} oninput={markDirty} /><label class="check-line"><input type="checkbox" bind:checked={item.equipped} onchange={markDirty} /> Equipped</label><button class="button button--quiet" onclick={() => { character!.equipment.splice(index,1); markDirty(); }}>Remove</button></div>{/each}</div></section>{/if}
  {#if activeTab === 'features'}<section class="panel"><h2>Features <button class="button button--small" onclick={() => { character!.features.push({name:'',description:'',source:''}); markDirty(); }}>Add feature</button></h2>{#each character.features as feature, index}<div class="feature-row"><input aria-label="Feature name" placeholder="Name" bind:value={feature.name} oninput={markDirty} /><input aria-label="Feature source" placeholder="Source" bind:value={feature.source} oninput={markDirty} /><textarea aria-label="Feature description" placeholder="Description" bind:value={feature.description} oninput={markDirty}></textarea><button class="button button--quiet" onclick={() => { character!.features.splice(index,1); markDirty(); }}>Remove</button></div>{/each}</section>{/if}
  {#if activeTab === 'notes'}<section class="notes-grid">{#each ['personalityTraits','ideals','bonds','flaws','backstory','additionalNotes'] as note}<label>{label(note)}<textarea value={character.notes[note as keyof typeof character.notes] as string} oninput={(e) => { character!.notes[note as keyof typeof character.notes] = (e.currentTarget as HTMLTextAreaElement).value as never; markDirty(); }}></textarea></label>{/each}<div class="panel panel--wide session-notes"><h2>Session Notes <button class="button button--small" onclick={addSessionNote}>Add session</button></h2>{#each character.notes.sessionNotes as session, index (session.id)}<div class="session-note"><div class="session-note__header"><input aria-label="Session title" bind:value={session.title} oninput={markDirty} /><input aria-label="Session date" type="date" bind:value={session.date} oninput={markDirty} /><button class="button button--quiet" onclick={() => { character!.notes.sessionNotes.splice(index, 1); markDirty(); }}>Delete</button></div><textarea aria-label="Session notes" placeholder="Session notes..." bind:value={session.notes} oninput={markDirty}></textarea></div>{/each}{#if character.notes.sessionNotes.length === 0}<p class="muted">Keep a separate note for each session.</p>{/if}</div></section>{/if}
 </article>
{/if}
